-- ========================================
-- FIX ALL MISSING ENUM VALUES
-- ========================================

-- 1. SessionStatus (8 values expected)
-- Already fixed: ACTIVE, IDLE, ENDED, WITH_OPERATOR, RESOLVED, NOT_RESOLVED, WAITING_CLIENT, CANCELLED

-- 2. SenderType (4 values expected)
ALTER TYPE "SenderType" ADD VALUE IF NOT EXISTS 'USER';
ALTER TYPE "SenderType" ADD VALUE IF NOT EXISTS 'BOT';
ALTER TYPE "SenderType" ADD VALUE IF NOT EXISTS 'OPERATOR';
ALTER TYPE "SenderType" ADD VALUE IF NOT EXISTS 'SYSTEM';

-- 3. TicketStatus (5 values expected)
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'OPEN';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'WAITING_USER';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'RESOLVED';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'CLOSED';

-- 4. Priority (4 values expected)
ALTER TYPE "Priority" ADD VALUE IF NOT EXISTS 'LOW';
ALTER TYPE "Priority" ADD VALUE IF NOT EXISTS 'MEDIUM';
ALTER TYPE "Priority" ADD VALUE IF NOT EXISTS 'HIGH';
ALTER TYPE "Priority" ADD VALUE IF NOT EXISTS 'URGENT';

-- 5. ContactMethod (4 values expected)
ALTER TYPE "ContactMethod" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "ContactMethod" ADD VALUE IF NOT EXISTS 'PHONE';
ALTER TYPE "ContactMethod" ADD VALUE IF NOT EXISTS 'WHATSAPP';
ALTER TYPE "ContactMethod" ADD VALUE IF NOT EXISTS 'CHAT';

-- 6. QueueStatus (4 values expected)
ALTER TYPE "QueueStatus" ADD VALUE IF NOT EXISTS 'WAITING';
ALTER TYPE "QueueStatus" ADD VALUE IF NOT EXISTS 'ASSIGNED';
ALTER TYPE "QueueStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "QueueStatus" ADD VALUE IF NOT EXISTS 'TIMEOUT';

-- 7. SLAStatus (5 values expected)
ALTER TYPE "SLAStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "SLAStatus" ADD VALUE IF NOT EXISTS 'RESPONSE_MET';
ALTER TYPE "SLAStatus" ADD VALUE IF NOT EXISTS 'RESOLUTION_MET';
ALTER TYPE "SLAStatus" ADD VALUE IF NOT EXISTS 'VIOLATED';
ALTER TYPE "SLAStatus" ADD VALUE IF NOT EXISTS 'ESCALATED';
